name: HunkleberryGeneral

main: com.LandOfGlendria.HunkleberryGeneral.HunkleberryGeneral

version: 0.80

website: TBD

description: Friendly general command plugin. Fixed by needaxeo

author: Glen McNeilley

commands:

 get:
  description: 
  usage: 
 give:
  description: 
  usage: 
 getblock:
  description: 
  usage: 
 giveblock:
  description: 
  usage: 
 clearinv:
  description: 
  usage: 
 clearinvall:
  description: 
  usage: 
 listinv:
  description: 
  usage: 
 matcontains:
  description: 
  usage: 
 heal:
  description: 
  usage: 
 setname:
  description: 
  usage: 
 who:
  description: 
  usage: 
 playerinfo:
  description: 
  usage: 
 colorchart:
  description: 
  usage: 
 setspawn:
  description: 
  usage: 
 setcompass:
  description: 
  usage: 
 compass:
  description: 
  usage: 
 loc:
  description: 
  usage: 
 sights:
  description: 
  usage: 
 see:
  description: 
  usage: 
 leap:
  description: 
  usage: 
 fling:
  description: 
  usage: 
 gather:
  description: 
  usage: 
 spawn:
  description: 
  usage: 
 strata:
  description: 
  usage: 
 motd:
  description: 
  usage: 
 slay:
  description: 
  usage: 
 cleardrops:
  description: 
  usage: 
 gettime:
  description: 
  usage: 
 time:
  description: 
  usage: 
 listworlds:
  description: 
  usage: 
 loadworld:
  description: 
  usage: 
 createworld:
  description: 
  usage: 
 setworldtype:
  description: 
  usage: 
 worldloadlist:
  description: 
  usage: 
 hg_help:
  description: 
  usage: 
 listplugins:
  description: 
  usage: 
 bounce:
  description: 
  usage: 
 unbounce:
  description: 
  usage: 
 forcebounce:
  description: 
  usage: 
 reloadbounced:
  description: 
  usage: 
 listbounced:
  description: 
  usage: 
 loadplugin:
  description: 
  usage: 
 disableplugin:
  description: 
  usage: 
 enableplugin:
  description: 
  usage: 
 clearplugins:
  description: 
  usage: 
 writehtml:
  description: 
  usage: 
 writebukkit:
  description: 
  usage: 
 writeyaml:
  description: 
  usage: 
 setcommandalias:
  description: 
  usage: 
 setserverallow:
  description: 
  usage: 
 setopsonly:
  description: 
  usage: 
 setpermissions:
  description: 
  usage: 
 saveproperties:
  description: 
  usage: 
 reloadproperties:
  description: 
  usage: 
