name: HunkleberryGeneral

main: com.LandOfGlendria.HunkleberryGeneral.HunkleberryGeneral

version: 0.66

website: TBD

description: Friendly general command plugin.

author: Glen McNeilley
